# Generated by Django 4.2.26 on 2026-09-13 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_personal_workspaces(apps, schema_editor):
    """Give existing Client users a personal workspace and migrate projects."""
    User = apps.get_model("auth", "User")
    Workspace = apps.get_model("core", "Workspace")
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    Project = apps.get_model("core", "Project")

    for user in User.objects.filter(groups__name="Client").distinct():
        workspace = Workspace.objects.create(
            name=f"{user.username}'s workspace", kind="personal"
        )
        WorkspaceMembership.objects.create(workspace=workspace, user=user, role="admin")
        Project.objects.filter(client=user, workspace__isnull=True).update(
            workspace=workspace
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_projectmembership_projectinvitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of this workspace.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("personal", "Personal"), ("company", "Company")],
                        db_index=True,
                        default="personal",
                        help_text=(
                            "Whether this workspace is personal or company-owned."
                        ),
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this workspace was created.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("client", "Client")],
                        db_index=True,
                        default="client",
                        help_text="The user's role within this workspace.",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this membership currently grants access.",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this membership was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user granted workspace access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="The workspace this membership belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace membership",
                "verbose_name_plural": "workspace memberships",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The opaque invitation identifier.",
                        unique=True,
                        verbose_name="invitation token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="The current invitation lifecycle state.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this invitation was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitee accepted this invitation.",
                        null=True,
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        help_text="The client who may accept this invitation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_workspace_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invitee",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        help_text="The administrator who sent this invitation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_workspace_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inviter",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text=(
                            "The company workspace this invitation grants access to."
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace invitation",
                "verbose_name_plural": "workspace invitations",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="The workspace containing this project.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.workspace",
                verbose_name="workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="unique_workspace_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspaceinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("workspace", "invitee"),
                name="unique_pending_workspace_invitation",
            ),
        ),
        migrations.RunPython(create_personal_workspaces, migrations.RunPython.noop),
    ]
